tickertape/feeds/urls.py
from django.conf.urls import *
from django.views.generic import TemplateView
from views import *

urlpatterns = patterns('',
    url(r'^entries$', entries, name='entries'),
    url(r'^entries/(?P<source_id>.+)$', entries, name='source_entries'),
    url(r'^pull$', pull_feeds, name='pull'),
    url(r'^upload$', upload_opml_file, name='upload'),
)

tickertape/tickertape/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tickertape.views.home', name='home'),
    # url(r'^tickertape/', include('tickertape.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^feeds/', include('feeds.urls')),
)

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

tickertape/feeds/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Group(models.Model):
	user = models.ForeignKey(User)
	name = models.CharField(max_length=200)
	created = models.DateTimeField(editable=False)
	modified = models.DateTimeField()

	@property
	def entry_count(self):
		entry_count = 0
		user_sources = UserSource.objects.filter(group=self)
		for user_source in user_sources:
			entry_count += user_source.source.entry_count
		return entry_count

	def save(self, *args, **kwargs):
	    ''' On save, update timestamps '''
	    if not self.id:
	        self.created = datetime.datetime.today()

	    self.modified = datetime.datetime.today()
	    super(Group, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.name


class Source(models.Model):
	text = models.CharField(max_length=200)
	title = models.CharField(max_length=200)
	icon_url = models.URLField(max_length=255)
	xml_url = models.URLField(max_length=200)
	html_url = models.URLField(max_length=255)
	feed_type = models.CharField(max_length=200)
	updated_parsed = models.DateTimeField(null=True, blank=True) #feed timestamp
	created = models.DateTimeField(editable=False) #database timestamp
	modified = models.DateTimeField() #database timestamp

	@property
	def entry_count(self):
		return self.entry_set.count()

	def save(self, *args, **kwargs):
	    ''' On save, update timestamps '''
	    if not self.id:
	        self.created = datetime.datetime.today()

	    self.modified = datetime.datetime.today()
	    super(Source, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.title

class UserSource(models.Model):
	user = models.ForeignKey(User)
	source = models.ForeignKey(Source)	
	group = models.ForeignKey(Group, null=True, blank=True, default=None)
	created = models.DateTimeField(editable=False)
	modified = models.DateTimeField()

	def save(self, *args, **kwargs):
	    ''' On save, update timestamps '''
	    if not self.id:
	        self.created = datetime.datetime.today()

	    self.modified = datetime.datetime.today()
	    super(UserSource, self).save(*args, **kwargs)




class Entry(models.Model):
	class Meta:
		verbose_name_plural = 'entries'
		ordering = ['published_parsed']

	source = models.ForeignKey(Source)
	feed_id = models.CharField(max_length=255)
	title = models.CharField(max_length=255)
	summary = models.TextField()
	author_name = models.CharField(max_length=255)	
	author_href = models.URLField(max_length=255)	
	author_email = models.CharField(max_length=255)
	comments_href = models.URLField(max_length=255)
	content = models.TextField()
	contributors = models.TextField()
	link = models.URLField(max_length=255)
	links = models.TextField()
	raw = models.TextField()
	created_parsed = models.DateTimeField(null=True, blank=True) #feed timestamp
	expired_parsed = models.DateTimeField(null=True, blank=True) #feed timestamp
	published_parsed = models.DateTimeField(null=True, blank=True) #feed timestamp
	updated_parsed = models.DateTimeField(null=True, blank=True) #feed timestamp
	created = models.DateTimeField(editable=False) #database timestamp
	modified = models.DateTimeField() #database timestamp

	def save(self, *args, **kwargs):
	    ''' On save, update timestamps '''
	    if not self.id:
	        self.created = datetime.datetime.today()

	    self.modified = datetime.datetime.today()
	    super(Entry, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.title		

tickertape/feeds/forms.py
from django import forms

class UploadOpmlFileForm(forms.Form):
    file  = forms.FileField()

tickertape/feeds/views.py
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from forms import UploadOpmlFileForm
from models import Source, Group, Entry, UserSource
import xml.etree.ElementTree as ET
import feedparser
from time import mktime
from datetime import datetime


@login_required
def upload_opml_file(request):
    if request.method == 'POST':
        form = UploadOpmlFileForm(request.POST, request.FILES)
        if form.is_valid():
        	#opml_file = request.FILES['file'].read()
        	#tree = ET.parse(opml_file)
        	#root = tree.getroot()
        	#for outline in root.iter('outline'):
			#	source = Source(user=request.user, xml_url=outline.get('xmlUrl'))
			#	source.save()

			Source.objects.all().delete()
			Group.objects.all().delete()

			group = None
			for event, elem in ET.iterparse(request.FILES['file']):
				#import pdb; pdb.set_trace()
				if elem.tag == 'body':
					outlines = list(elem)

					for outline in outlines:
						if 'xmlUrl' not in outline.attrib:
							group = Group(user=request.user, name=outline.attrib['title']) 
							group.save()

							children = list(outline)
							for child in children:
								source = Source()
								source.text = child.attrib['text']
								source.title = child.attrib['title']
								source.feed_type = child.attrib['type'] 
								source.xml_url = child.attrib['xmlUrl']
								source.html_url = child.attrib['htmlUrl']
								source.save()

								user_source = UserSource(user=request.user, source=source, group=group)
								user_source.save()		
						elif 'xmlUrl' in outline.attrib:
							print outline.attrib
							source = Source()
							source.text = outline.attrib['text']
							source.title = outline.attrib['title']
							source.feed_type = outline.attrib['type'] 
							source.xml_url = outline.attrib['xmlUrl']
							source.html_url = outline.attrib['htmlUrl']
							source.save()	

							user_source = UserSource(user=request.user, source=source)
							user_source.save()		

			return HttpResponseRedirect( reverse('entries') )
    else:
        form = UploadOpmlFileForm()

    return render_to_response('feeds/upload_opml.html', {'form': form}, context_instance=RequestContext(request)) 



@login_required
def entries(request, source_id=None, entries_per_page=200):
	user_sources = UserSource.objects.filter(user=request.user)
	if source_id:
		entry_list = Entry.objects.filter(source__usersource__user=request.user,source=source_id).order_by('-published_parsed')
	else:
		entry_list = Entry.objects.filter(source__usersource__user=request.user).order_by('-published_parsed')

	paginator = Paginator(entry_list, entries_per_page)
	groups = Group.objects.filter(user=request.user)

	page = request.GET.get('page')
	try:
		entries = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		entries = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		entries = paginator.page(paginator.num_pages)

	return render_to_response('feeds/entries.html', {'user_sources': user_sources, 'groups': groups, 'entries': entries}, context_instance=RequestContext(request))


@login_required
def pull_feeds(request):
	sources = Source.objects.filter(usersource__user=request.user)

	for source in sources:
		if source.xml_url:
			d = feedparser.parse(source.xml_url)

			#update source with attributes from feed
			if 'icon' in d.feed:
				source.icon_url = d.feed.icon
			if 'updated_parsed' in d.feed and d.feed.updated_parsed is not None:
				source.updated_parsed = datetime.fromtimestamp(mktime(d.feed.updated_parsed))
			source.save()

			#print [field for field in d]
			for e in d['entries']:
				if 'published_parsed' in e:
					entry_published_date = datetime.fromtimestamp(mktime(e.published_parsed)) #feed timestamp
					if source.updated_parsed is None or entry_published_date>source.updated_parsed:
						entry = Entry(source=source, title=e.title, raw=e)
						if 'author_detail' in e:
							if 'name' in e.author_detail:
								entry.author_name = e.author_detail.name	
							if 'href' in e.author_detail:
								entry.author_href = e.author_detail.href
							if 'email' in e.author_detail:
								entry.author_email = e.author_detail.email
						if 'comments' in e:
							entry.comments_href = e.comments
						if 'content' in e:
							entry.content = e.content
						if 'contributors' in e:
							entry.contributors = e.contributors
						if 'link' in e:
							entry.link = e.link
						if 'links' in e:
							entry.links = e.links
						if 'created_parsed' in e:
							entry.created_parsed = datetime.fromtimestamp(mktime(e.created_parsed)) #feed timestamp
						if 'expired_parsed' in e:
							entry.expired_parsed = datetime.fromtimestamp(mktime(e.expired_parsed)) #feed timestamp
						if 'published_parsed' in e:
							entry.published_parsed = datetime.fromtimestamp(mktime(e.published_parsed)) #feed timestamp
						if 'updated_parsed' in e:
							entry.updated_parsed = datetime.fromtimestamp(mktime(e.updated_parsed)) #feed timestamp

						if 'summary' in e:
							entry.summary = e.summary
						entry.save()
				else:
					print 'Entry with no Publication date: %s' % e

	return HttpResponseRedirect( reverse('entries') )

tickertape/feeds/templates/feeds/entries.html
{% extends "bootstrap/secondary.html" %}

{% block sidebar %}
<div class="sidebar-nav-fixed">
	<div class="accordion" id="sidebar-accordion">
		<div class="accordion-group">
			<div class="accordion-heading">
				<div class="accordion-toggle" data-parent="#sidebar-accordion">
					<a href="{% url 'feeds.views.entries' %}">
						<i class="icon-globe pull-left" style="margin-right: 10px;"></i> 
						<strong>All items</strong> <span class="badge pull-right">{{ entries|length }}</span>
					</a>
				</div>
			</div>
		</div>
		{% for user_source in user_sources %}
			{% if not user_source.group %}
			<div class="accordion-group">
				<div class="accordion-heading">
					<div class="accordion-toggle clearfix" data-parent="#sidebar-accordion">
						<a href="{% url 'feeds.views.entries' source_id=user_source.source.id %}">
							<i class="icon-chevron-right pull-left" style="margin-right: 10px;"></i> 
							<span class="truncate pull-left" style="width:67%;">{{ user_source.source.title }}</span> <span class="badge pull-right">{{ user_source.source.entry_count }}</span>
						</a>
					</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
		{% for group in groups %}
		<div class="accordion-group">
			<div class="accordion-heading">
				<div class="accordion-toggle clearfix" data-toggle="collapse" data-parent="#sidebar-accordion" href="#collapse-{{ group.id }}">
					<i class="icon-folder-close pull-left" style="margin-right: 10px;"></i> 
					<span class="truncate pull-left" style="width:67%;">{{ group.name }}</span> <span class="badge pull-right">{{ group.entry_count }}</span>
				</div>
			</div>
		    <div id="collapse-{{ group.id }}" class="accordion-body collapse">
		      <div class="accordion-inner">
				{% for user_source in group.usersource_set.all %}
					<a href="{% url 'feeds.views.entries' source_id=user_source.source.id %}" class="clearfix">
						<i class="icon-chevron-right pull-left" style="margin-right: 10px;"></i> 
						<span class="pull-left truncate" style="width:67%;">{{ user_source.source.title }}</span> 
						<span class="badge pull-right">{{ user_source.source.entry_count }}</span>
					</a>
				{% endfor %}
		      </div>
		    </div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

{% block content %}
	<div class="accordion" id="entries-accordion">
	{% for entry in entries %}
		<div class="accordion-group">
			<div class="accordion-heading">
				<div class="accordion-toggle">
					<div class="row-fluid entry-header">
			        	<span class="span2 truncate entry-header">{{ entry.source.title }}</span>
			        	<span class="span9 truncate entry-header" data-toggle="collapse" data-parent="#entries-accordion" href="#collapse-entry-{{ entry.id }}">
			        		<b>{{ entry.title }}</b> - {{ entry.summary }}
			        	</span>
			        	<span class="span1 entry-header">
			        		<a href="{{ entry.link }}" target="_blank" class="external-link pull-right"><i class="icon-share-alt"></i></a>
			        	</span>
					</div><!--/row-->
				</div>
			</div>
		    <div id="collapse-entry-{{ entry.id }}" class="accordion-body collapse">
		      <div class="accordion-inner">
					<div class="row-fluid">
			        	<span class="span10 offset2">
			        		{% if entry.content %}
			        			{{ entry.content }}
			        		{% else %}
			        			{{ entry.summary }}
			        		{% endif %}
			        	</span>
					</div><!--/row-->		      	
		      </div>
		    </div>
		</div>
	{% endfor %}
	</div>

	<div class="pagination">
	  <ul>
        {% if entries.has_previous %}
            <li><a href="?page={{ entries.previous_page_number }}">Prev</a></li>
        {% endif %}
	    <li><a href="#">Page {{ entries.number }} of {{ entries.paginator.num_pages }}</a></li>
        {% if entries.has_next %}
            <li><a href="?page={{ entries.next_page_number }}">Next</a></li>
        {% endif %}
	  </ul>
	</div>
{% endblock %}

tickertape/feeds/templates/feeds/feeds.html
{% extends "bootstrap/secondary.html" %}

tickertape/feeds/templates/feeds/groups.html
groups.html

tickertape/feeds/templates/feeds/upload_opml.html
{% extends "bootstrap/secondary.html" %}

{% block content %}
<div class="row-fluid">
	<form class="form-horizontal" name="uploadForm" action="{% url "upload" %}" enctype="multipart/form-data" method="post">
		{% csrf_token %}
	  <div class="control-group">
	    <label class="control-label" for="file">OMPL file</label>
	    <div class="controls">
	      <input id="file" type="file" name="file" size="200"/>
	    </div>
	  </div>
	  <div class="control-group">
	    <div class="controls">
	      <button type="submit" class="btn">Upload</button>
	    </div>
	  </div>
	</form>
</div><!--/row-->
{% endblock %}